Traceback (most recent call last):
  File "tiling_wsi.py", line 144, in <module>
    wsi_path = sys.argv[1]
IndexError: list index out of range
